version: '3.8'
services:
  client:
    container_name: werkzeugverwaltung_client
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  server: 
    container_name: werkzeugverwaltung_server
    build: 
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    