version: '3.8'
services:
  client:
    container_name: werkzeugverwaltung_client
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  server: 
    container_name: werkzeugverwaltung_server
    build: 
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    
  mysql:
    container_name: werkzeugverwaltung_mysql
    image: mysql:8
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: 'password'
    ports:
          - '3306:3306'
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql